### PR TITLE
Add Mayhem Support

### PR DESCRIPTION
**Pull request by mahaloz**

### CODE REVIEW

**Comment by xansec** [comment]
LGTM!

**Comment by xansec** [comment]
After merging, this isn't working anymore. Please fork and resolve. https://github.com/mayhemheroes/rp/actions/workflows/mayhem.yml

**Comment by mahaloz** [comment]
@xansec it looks like the lines you added are causing it to break. Could you look at them again?

**Comment by xansec** [comment]
Yes, I made a few changes. The action was failing after merge. Initially, I noticed the binary could not be found:
https://github.com/mayhemheroes/rp/runs/6781557628?check_suite_focus=true#step:5:1102
Refer to this commit: https://github.com/mayhemheroes/rp/commit/9141b4e189463361b691a8a8270ff8dbe7623107
Then, I noticed the same issue with the Mayhemfile: https://github.com/mayhemheroes/rp/runs/6781791201?check_suite_focus=true#step:6:77
The corresponding run: https://mayhem.forallsecure.com/mayhemheroes/rp/rp-lin-x64/1
described that it could not find the command referenced, which makes sense because this did not exist on the image.
Refer to this commit: https://github.com/mayhemheroes/rp/commit/641dc7116fafe676e289872da1cd33eea7582de7
After which, I noticed that the Mayhem run failed outright, so I decided to add some valid files to the corpus: https://github.com/mayhemheroes/rp/runs/6782826416?check_suite_focus=true#step:6:77
This run: https://mayhem.forallsecure.com/mayhemheroes/rp/rp-lin-x64/2
failed due to a timeout. Refer to this commit: https://github.com/mayhemheroes/rp/commit/b7bd3776c76e57145c9fe28850843bdcda6c0dff
(this adds some binaries to the corpus, which the target ingests). After looking at that latest run, it appears I just need to correct the Dockerfile:
```
#14 [stage-1 3/3] RUN cp /bin /testsuite
#14 0.199 cp: -r not specified; omitting directory '/bin'
#14 ERROR: executor failed running [/bin/sh -c cp /bin /testsuite]: exit code: 1
------
 > [stage-1 3/3] RUN cp /bin /testsuite:
#14 0.199 cp: -r not specified; omitting directory '/bin'
```
In any case, I've reverted my commits so that we can start fresh and figure out what's wrong.

**Comment by xansec** [comment]
After reverting the commits, I get the same error about the binary not being found:
https://github.com/mayhemheroes/rp/actions/runs/2464223488

**Comment by xansec** [comment]
I reverted reverting my changes: https://github.com/mayhemheroes/rp/commit/5d8fffbd352befca55ebcd1fce0818f31beeb5f3
And I updated the command timeout, as this is a slow target. https://mayhem.forallsecure.com/mayhemheroes/rp/rp-lin-x86-64/2

This should be fine for now, but keep an eye on this target, as it is currently slow and there may be more upstream breaking changes in the next 30 days.

**Comment by mahaloz** [comment]
Ok got it

**Pull request merged**
